name: align_positioned
description: Greatly simplifies layouts which are difficult to implement with Columns and Rows, by letting you declaratively position and resize widgets in relation to one another.
version: 4.0.0
# author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/align_positioned

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  matrix4_transform: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

