name: align_positioned
description: When your desired layout or animation is too complex for Columns and Rows, this widget is a life saver. It lets you declaratively position/size its child in complex ways.

version: 1.2.4
author: Marcelo Glasberg <marcglasberg@gmail.com>
homepage: https://github.com/marcglasberg/align_positioned

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  matrix4_transform: ^1.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

